version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Build Tools
          command: apt-get update && apt-get -y install build-essential
      - run:
          name: Install Cmake
          command: apt-get -y install cmake
      - run:
          name: List Directory Contents
          command: ls -a
      - run:
          name: Run Cmake
          command: cmake .