version: 2
jobs:
  build:
    docker:
      - image: bitflipsoftware/cmake-gcc:1.1
    steps:
      - checkout
      - run:
          name: Print Cmake Version
          command: cmake --version
      - run:
          name: Run Cmake
          command: mkdir -p cibuild && cd cibuild && cmake ../
      - run:
          name: pwd
          command: pwd
      # - run:
      #     name: Run Cmake
      #     command: cmake .
      # - run:
      #     name: List Directory Contents
      #     command: ls -a
      # - run:
      #     name: Compile Code
      #     command: make
      # - run:
      #     name: List Directory Contents
      #     command: ls -a
