version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Build Tools
          command: apt-get update && apt-get -y install build-essential
      - run:
          name: Install Cmake
          command: apt remove cmake
          command: apt purge --auto-remove cmake
          command: version=3.9
          command: build=6
          command: wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          command: tar -xzvf cmake-$version.$build.tar.gz
          command: cd cmake-$version.$build/ && ls -a
      - run:
          name: Print Cmake Version
          command: cmake --version
      - run:
          name: List Directory Contents
          command: ls -a
      - run:
          name: Run Cmake
          command: cmake .
      - run:
          name: List Directory Contents
          command: ls -a
      - run:
          name: Compile Code
          command: make
      - run:
          name: List Directory Contents
          command: ls -a
