version: 2
jobs:
  build:
    docker:
      - image: bitflipsoftware/cmake-gcc:1.1
    steps:
      - checkout
      
      # Download cache
      - restore_cache:
          keys:
          - mxcache-{{ checksum ".circleci/cache-lock" }}
          # fallback to using the latest cache if no exact match is found
          - mxcache-

      - run:
          name: Print Cmake Version
          command: cmake --version
      - run:
          name: Run Cmake
          command: mkdir -p cibuild && cd cibuild && cmake ../
      - run:
          name: Compile
          command: cd cibuild && make


      - save_cache:
          paths:
            - cibuild

          key: mxcache-{{ checksum ".circleci/cache-lock" }}