version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Build Tools
          command: apt-get update && apt-get -y install build-essential
      - run:
          name: Install Cmake
          command: apt-get -y install cmake
      - run:
          name: create build dir
          command: mkdir build && cd build
      - run:
          name: run cmake
          command: cmake ..